name: WakaTime Stats Update
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # CRUCIAL FIX
          
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_USERNAME: Froillan123  # Must match exactly
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_COUNT: "True"
          SHOW_LOC_CHART: "False"